### ISSUE TITLE
picks page list order by VICTORIES desc failed

### ISSUE THREAD

**Issue by sssssssq** [chinleung/rtapicks-issues#13]

**Comment by chinleung** [comment]
@sssssssq What do you mean has failed? I've just tried it and it it working properly. You can try it with this link: https://www.rtapicks.info/resources/picks?picks_order=victories&picks_direction=desc

![image](https://user-images.githubusercontent.com/19669331/71625056-c441ac00-2bb3-11ea-9ee1-aeac62e4b4ae.png)

If you want to order by percentage, you must check the `Percentage` option in the filters.

**Comment by chinleung** [comment]
Closing due to no response.
