### ISSUE TITLE
上赛季最后两天数据不存在

### ISSUE THREAD

**Issue by sssssssq** [chinleung/rtapicks-issues#17]
联赛不更新吗？

上赛季最后两天数据也没有

**Comment by chinleung** [comment]
> 联赛不更新吗？
> 
> 上赛季最后两天数据也没有

该应用程序将在第12季正式发布，并带有一个新的数据库。因此，我正在本赛季的最后2天对该应用程序执行更新，而不是获取一些将被擦除的数据。
